# Generated by Django 5.1.6 on 2025-03-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
