# Generated by Django 5.1.6 on 2025-03-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_resume_resume_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_data',
            field=models.JSONField(blank=True, default={'r': 'reerf'}, null=True),
        ),
    ]
