# Generated by Django 5.1.6 on 2025-03-02 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_resume_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='note_image',
            field=models.ImageField(blank=True, null=True, upload_to='Notes-Image', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
