# Generated by Django 5.1.6 on 2025-03-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_notes_note_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='context',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='selected_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
