# Generated by Django 5.1.6 on 2025-03-10 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_notes_context_notes_section_notes_selected_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='note_image',
        ),
        migrations.AddField(
            model_name='notes',
            name='note_file',
            field=models.FileField(blank=True, null=True, upload_to='Notes-File', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
    ]
