# Generated by Django 5.1.6 on 2025-03-10 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_remove_notes_note_image_notes_note_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_file',
            field=models.FileField(blank=True, null=True, upload_to='Notes-File', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'jpeg', 'png', 'svg'])]),
        ),
    ]
