# Generated by Django 5.1.6 on 2025-03-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_alter_notes_note_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template_type',
            field=models.IntegerField(blank=True, choices=[(1, 'default'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'), (6, 'six')], null=True),
        ),
    ]
