# Generated by Django 5.1.6 on 2025-04-02 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_alter_notes_note_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_file',
            field=models.FileField(blank=True, null=True, upload_to='Notes-File', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'jpeg', 'png', 'svg', 'jpg', 'webp'])]),
        ),
    ]
