# Generated by Django 5.1.6 on 2025-04-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_alter_notes_note_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='parsing_status',
            field=models.CharField(choices=[('not_parsed', 'Not Parsed'), ('parsing', 'Parsing in Progress'), ('parsed', 'Parsed Successfully'), ('failed', 'Parsing Failed')], default='not_parsed', max_length=20),
        ),
    ]
